# Use Node.js configuration.
language: node_js

# Test the latest and LTS releases >= LTS Dubnium (10).
node_js:
  - lts/dubnium
  - lts/erbium
  - node

# All of the operating systems!
# Note: Windows support is iffy.
os:
  - linux
  - osx
  - windows

# Don't build arbitrary branches, just pull requests + master + semver tags.
branches:
  only:
    - master
    - "/^v\\d+\\.\\d+\\.\\d+$/"
